#
# Copyright (C) 2019 Assured Information Security, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#
# Configuration
#
language: cpp
dist: xenial

#
# Cache Dependencies
#
cache:
  directories:
  - ../cache

#
# Build Dependencies
#
before_script:

  #
  # Cache / Depends
  #
  - mkdir -p ../cache

  #
  # Build Enviornment
  #
  - mkdir -p build
  - cd build

  #
  # Update GCC
  #
  - |
    if [[ -f "/usr/bin/gcc-8" ]]; then
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
    fi

  #
  # Update CMake
  #
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.13/cmake-3.13.4-Linux-x86_64.tar.gz"
      mkdir cmake
      travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=$(pwd)/cmake/bin:${PATH}
    fi

#
# Build Matrix
#
matrix:
  include:

  #
  # Doxygen
  #
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - doxygen
    env:
      - TEST="Doxygen"
    script:
      - cd ..
      - doxygen .doxygen.txt
      - |
        if [[ -s doxygen_warnings.txt ]]; then
          echo "You must fix doxygen before submitting a pull request"
          echo ""
          cat doxygen_warnings.txt
          exit -1
        fi

  #
  # Git Check
  #
  - os: linux
    env:
      - TEST="Git Check"
    script:
      - |
        if [[ -n $(git diff --check HEAD^) ]]; then
          echo "You must remove whitespace before submitting a pull request"
          echo ""
          git diff --check HEAD^
          exit -1
        fi

  #
  # Format
  #
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-8
        packages:
          - clang-format-8

    env:
      - TEST="Format"
    script:
      - sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-8 100
      - cmake ..
      - make format
      - |
        if [[ -n $(git diff) ]]; then
          echo "You must run make format before submitting a pull request"
          echo ""
          git diff
          exit -1
        fi

  #
  # Unit tests and static analysis
  #
  - os: linux
    env:
      - TEST="Tests"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8
          - g++-8
    script:
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
      - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
      - git clone https://github.com/catchorg/catch2.git
      - cd catch2
      - mkdir build
      - cd build
      - cmake -DBUILD_TESTING=OFF ..
      - sudo make install
      - cd ../../
      - cmake -DBUILD_TESTS=ON ..
      - make
      - make test

  #
  # Xen driver
  #
  - os: linux
    env:
      - TEST="Xen"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8
          - g++-8
    script:
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
      - git clone https://github.com/connojd/xen.git -b xue
      - cp ../include/xue.h xen/xen/include/xue.h
      - cd xen
      - ./configure --disable-tools --disable-stubdom --disable-docs
      - make dist-xen -j3

  #
  # Xen driver
  #
  - os: linux
    env:
      - TEST="UEFI"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8
          - g++-8
          - gnu-efi
    script:
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
      - cd ../test
      - make
